"""empty message

Revision ID: 460ac76c6e10
Revises: 360364f0db33
Create Date: 2018-10-05 19:54:09.846759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460ac76c6e10'
down_revision = '360364f0db33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['bk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['frontuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('common_post')
    # ### end Alembic commands ###
