"""empty message

Revision ID: 6f8c6a6dffd6
Revises: cbb8e5375d6a
Create Date: 2018-09-28 14:45:42.338774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8c6a6dffd6'
down_revision = 'cbb8e5375d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lbt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bannerName', sa.String(length=20), nullable=False),
    sa.Column('imglink', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imglink'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lbt')
    # ### end Alembic commands ###
